using System;
using System.Collections.Generic;
using TombLib.LevelData;

namespace TombLib.LevelData.Compilers.TombEngine
{
    /// <summary>
    /// TombEngine Pathfinding System
    ///
    /// This file handles the high-level pathfinding data generation for TombEngine.
    ///
    /// ARCHITECTURE OVERVIEW:
    /// =====================
    /// 1. BOXES: Rectangular floor regions where enemies can walk. Generated by Dec_BuildBoxesAndOverlaps().
    /// 2. OVERLAPS: Connections between adjacent boxes. Define which boxes are reachable from each other.
    /// COORDINATE SYSTEM:
    /// ==================
    /// - X axis: horizontal (left/right in 2D view)
    /// - Z axis: horizontal (up/down in 2D view), Z=0 at bottom
    /// - Y axis: vertical (height), negative values are higher
    /// </summary>
    public sealed partial class LevelCompilerTombEngine
    {
        /// <summary>
        /// Main entry point for pathfinding data generation.
        ///
        /// This method orchestrates the entire pathfinding compilation process:
        /// 1. Fixes monkey swing flags on floor portals (inherited from rooms below)
        /// 2. Generates boxes and overlaps (Dec_BuildBoxesAndOverlaps)
        /// 3. Converts internal box format to TombEngine format
        ///
        /// OUTPUT DATA STRUCTURES:
        /// - _boxes: List of TombEngineBox (walkable rectangular areas)
        /// - _overlaps: List of TombEngineOverlap (connections between boxes with flags)
        /// </summary>
        private void BuildPathFindingData()
        {
            ReportProgress(48, "Building pathfinding data");

            // ===================================================================================
            // PHASE 1: Fix monkey swing flags on floor portals
            // ===================================================================================
            // When a sector has a floor portal, the monkey swing flag may be defined in a room below.
            // This pass ensures monkey swing info is correctly propagated through portal chains.
            foreach (var fixRoom in _tempRooms.Values)
            {
                for (int x = 0; x < fixRoom.NumXSectors; x++)
                {
                    for (int z = 0; z < fixRoom.NumZSectors; z++)
                    {
                        var sector = fixRoom.AuxSectors[x, z];
                        if (sector.FloorPortal != null)
                            sector.Monkey = FindMonkeyFloor(fixRoom.OriginalRoom, x, z);
                    }
                }
            }

            // ===================================================================================
            // PHASE 2: Generate boxes and overlaps
            // ===================================================================================
            // This creates dec_boxes and dec_overlaps lists.
            Dec_BuildBoxesAndOverlaps();

            // ===================================================================================
            // PHASE 3: Convert to TombEngine format
            // ===================================================================================
            // Convert internal overlap format to final format
            _overlaps = new List<TombEngineOverlap>();
            _overlaps.AddRange(dec_overlaps);

            // Convert internal box format to TombEngine format
            _boxes = new List<TombEngineBox>();

            for (var i = 0; i < dec_boxes.Count; i++)
            {
                int flags = 0;

                if (dec_boxes[i].Splitter)
                    flags |= BoxFlags.Splitter;

                if (dec_boxes[i].Water)
                    flags |= BoxFlags.Water;

                if (dec_boxes[i].Shallow)
                    flags |= BoxFlags.Shallow;

                if (dec_boxes[i].Slope)
                    flags |= BoxFlags.Slope;

                var box = new TombEngineBox()
                {
                    Xmin = dec_boxes[i].Xmin,                              // Left boundary (in sectors)
                    Xmax = dec_boxes[i].Xmax,                              // Right boundary (in sectors)
                    Zmin = dec_boxes[i].Zmin,                              // Bottom boundary (in sectors)
                    Zmax = dec_boxes[i].Zmax,                              // Top boundary (in sectors)
                    TrueFloor = -dec_boxes[i].Height,                      // Floor height (negated: TR uses inverted Y)
                    OverlapIndex = dec_boxes[i].OverlapIndex,              // Index into _overlaps array (-1 if none)
                    Flags = flags
                };

                _boxes.Add(box);
            }

            ReportProgress(52, "    Number of boxes: " + _boxes.Count);
            ReportProgress(52, "    Number of overlaps: " + _overlaps.Count);
            ReportProgress(52, "    Number of sector box variant sets: " + _sectorBoxVariants.Count);
        }

    }
}
